wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/All_GeneBody_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/All_Intergenic_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/All_Promoters_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/CattlePig_GeneBody_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/CattlePig_Intergenic_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/CattlePig_Promoters_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/HumanMouse_GeneBody_HumanCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/HumanMouse_Intergenic_HumanCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/HumanMouse_Promoters_HumanCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/Mammalian_GeneBody_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/Mammalian_Intergenic_PigCoords.bed
wget -c http://farm.cse.ucdavis.edu/%7Eckern/Nature_Communications_2020/Regulatory_Elements/Conserved/Mammalian_Promoters_PigCoords.bed